---
# Update hosts that use the apt package manager.
- name: Update hosts using the apt package manager
  hosts: all
  tags: apt

  tasks:
   - name: Update Apt Cache
     ansible.builtin.apt:
      update_cache: true

   - name: Update all packages to latest version from Apt
     ansible.builtin.apt:
      name: "*"
      state: latest # noqa package-latest

# Update hosts that use the dnf package manager.
- name: Update hosts using the dnf package manager
  tags: dnf

  tasks:
   - name: Update all packages to latest version from dnf
     ansible.builtin.dnf:
      name: "*"
      state: latest # noqa package-latest

# Update infra hosts that use the apt package manager.
- name: Update hosts using the apt package manager
  tags: infra

  tasks:
   - name: Update Apt Cache
     ansible.builtin.apt:
      update_cache: true

   - name: Update all packages to latest version from Apt
     ansible.builtin.apt:
      name: "*"
      state: latest # noqa package-latest

# Update infra hosts that use the apt package manager.
- name: Update Raspberry Pi hosts using the apt package manager
  tags: pi

  tasks:
   - name: Update Apt Cache
     ansible.builtin.apt:
      update_cache: true

   - name: Update all packages to latest version from Apt
     ansible.builtin.apt:
      name: "*"
      state: latest # noqa package-latest
# - name: Reboot
#   hosts: apt,dnf
#   tags: reboot

#   tasks:
#    - name: Reboot system after updates
#      ansible.builtin.reboot:
