---
# Playbook for doing patching using AWX.

# Update hosts that use the apt package manager.
- name: Update hosts using the apt package manager
  hosts: all
  tags: apt

  tasks:
   - name: Update Apt Cache
     ansible.builtin.apt:
      update_cache: true

   - name: Upgrading all packages with apt
     ansible.builtin.apt:
      name: "*"
      state: latest # noqa package-latest

# Update hosts that use the dnf package manager.
- name: Update hosts using the dnf package manager
  hosts: all
  tags: dnf

  tasks:
   - name: Update all packages to latest version from dnf
     ansible.builtin.dnf:
      name: "*"
      state: latest # noqa package-latest

# Update infra hosts that use the apt package manager.
- name: Update infra servers using apt
  hosts: all
  tags: infra

  tasks:
   - name: Update Apt Cache
     ansible.builtin.apt:
      update_cache: true

   - name: Upgrading all packages with apt
     ansible.builtin.apt:
      name: "*"
      state: latest # noqa package-latest

# Update infra hosts that use the apt package manager.
- name: Update Raspberry Pis with apt
  hosts: all
  tags: pi

  tasks:
   - name: Update Apt Cache
     ansible.builtin.apt:
      update_cache: true

   - name: Upgrading all packages with apt
     ansible.builtin.apt:
      name: "*"
      state: latest # noqa package-latest
- name: Reboot
  hosts: all
  tags: reboot

  tasks:
   - name: Reboot system after updates
     ansible.builtin.reboot:
